/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/desk/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Identidade do chamador e mesas acessíveis
         * @description Identidade do chamador e as mesas em que tem assento, com o papel em cada uma.
         */
        get: operations["deskGetMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/desk/invitations/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Aceitar convite de mesa
         * @description O assento é vinculado à conta logada. O e-mail da sessão precisa ser o mesmo do convite; divergência responde 403 com `code: invite_email_mismatch`.
         */
        post: operations["deskAcceptInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/desk/orgs/{org}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Perfil da mesa
         * @description Cadastro da mesa: nome, slug, CNPJ, registro CVM e situação.
         */
        get: operations["deskGetOrganization"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Atualizar a mesa
         * @description Altera o nome e as configurações da mesa (`settings.seatAssignment`: automatic ou manual).
         */
        patch: operations["deskUpdateOrganization"];
        trace?: never;
    };
    "/v1/desk/orgs/{org}/license": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Licença da mesa
         * @description Plano vigente e os limites do contrato: assentos, classes acompanhadas e validade. `expired=true` bloqueia as escritas com 402 (`license_required`); as leituras seguem abertas.
         */
        get: operations["deskGetLicense"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/desk/orgs/{org}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Membros da mesa
         * @description Assentos da mesa: papel (owner, admin, analyst, viewer), nome de exibição e situação.
         */
        get: operations["deskListMembers"];
        put?: never;
        /**
         * Atribuir assento a um membro da organização
         * @description Cria (ou reativa) o assento da mesa para uma pessoa que já é membro da organização na plataforma, com o papel dado. É o caminho de entrada quando `settings.seatAssignment` é `manual`; em `automatic` serve para fixar o papel antes da primeira visita. Respeita o limite de assentos do contrato (402 `license_required`).
         */
        post: operations["deskAssignSeat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/desk/orgs/{org}/members/{memberId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Alterar papel ou status de um membro
         * @description Muda o papel, o nome de exibição ou suspende/reativa um assento. Não remove a pessoa da organização na plataforma.
         */
        patch: operations["deskUpdateMember"];
        trace?: never;
    };
    "/v1/desk/orgs/{org}/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Convites da mesa
         * @description Convites da mesa com e-mail, papel, situação e validade.
         */
        get: operations["deskListInvitations"];
        put?: never;
        /**
         * Convidar alguém para a mesa
         * @description Cria um convite por e-mail com o papel dado e devolve o link de aceite. O assento nasce quando a pessoa aceita (`deskAcceptInvitation`).
         */
        post: operations["deskCreateInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/desk/orgs/{org}/invitations/{invitationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revogar convite pendente
         * @description Cancela um convite ainda não aceito.
         */
        delete: operations["deskRevokeInvitation"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/desk/orgs/{org}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Trilha de auditoria da mesa
         * @description Trilha de auditoria da mesa, mais recente primeiro, com paginação por cursor. `entity_id` recorta por classe ou cedente (CNPJ).
         */
        get: operations["deskListAudit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/desk/orgs/{org}/watchlists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Watchlists da mesa
         * @description Listas de acompanhamento da mesa, com tipo (`book` = o que a casa gere ou originou; `market` = o que ela observa) e a contagem de posições.
         */
        get: operations["deskListWatchlists"];
        put?: never;
        /**
         * Criar watchlist
         * @description Cria uma watchlist com nome, slug opcional, descrição e tipo (`book` ou `market`).
         */
        post: operations["deskCreateWatchlist"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/desk/orgs/{org}/watchlists/{list}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remover watchlist
         * @description Remove a watchlist e as posições acompanhadas nela.
         */
        delete: operations["deskDeleteWatchlist"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/desk/orgs/{org}/watchlists/{list}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Posições acompanhadas na watchlist
         * @description Posições acompanhadas na watchlist: CNPJ da classe ou do cedente, rótulo, relação com a mesa (`own`/`tracked`) e ordem.
         */
        get: operations["deskListWatchlistItems"];
        put?: never;
        /**
         * Incluir posições na watchlist
         * @description Inclusão em lote e idempotente: CNPJs já acompanhados são contados em `skipped` em vez de derrubar o lote. Aceita CNPJ com ou sem pontuação.
         */
        post: operations["deskAddWatchlistItems"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/desk/orgs/{org}/watchlists/{list}/items/{cnpj}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remover posição da watchlist
         * @description Tira uma posição da watchlist pelo CNPJ.
         */
        delete: operations["deskRemoveWatchlistItem"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/desk/orgs/{org}/watchlists/{list}/board": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Quadro da watchlist com os números do informe
         * @description Cruza as posições acompanhadas com o informe mensal da CVM na competência mais recente. Nenhum número é armazenado pela mesa: tudo vem do informe a cada leitura.
         */
        get: operations["deskGetWatchlistBoard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/desk/orgs/{org}/grid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Colunas da grade e catálogo de métricas disponíveis
         * @description As colunas escolhidas para a grade da mesa e o catálogo de métricas disponíveis, com rótulo, unidade e ajuda de cada uma.
         */
        get: operations["deskGetGrid"];
        /**
         * Definir as colunas da grade
         * @description Define as colunas da grade (até 30 métricas do catálogo de `deskGetGrid`), na ordem dada.
         */
        put: operations["deskSetGrid"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/desk/orgs/{org}/watchlists/{list}/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Alertas da watchlist na competência mais recente
         * @description Derivados na leitura a partir de três origens: limiar do regulamento da classe (`covenant`), regra configurada pela mesa (`rule`) e classe que parou de reportar (`reporting`). A leitura também REGISTRA no ledger append-only o que ainda não tinha sido observado, e devolve `first_detected_at` — é o que permite dizer 'desde quando' sem reconstruir o passado com as regras de hoje.
         */
        get: operations["deskListAlerts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/desk/orgs/{org}/alert-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ledger de alertas já observados
         * @description Append-only: cada linha é o registro imutável de um alerta que disparou, com o valor e o LIMIAR vigentes naquele instante. Editar uma regra depois não reescreve o passado. É o insumo do backtest de um sinal (lift, falso positivo, antecedência) e do 'o que mudou desde a última vez'.
         */
        get: operations["deskListAlertHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/desk/orgs/{org}/alerts/{key}/ack": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dar baixa (ou silenciar) um alerta
         * @description A baixa vale para a COMPETÊNCIA do alerta. O mesmo sinal na competência seguinte volta como novo.
         */
        post: operations["deskAcknowledgeAlert"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/desk/orgs/{org}/alert-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Regras de alerta da mesa
         * @description Regras de alerta da mesa: métrica, comparador, limiar na unidade da métrica, severidade e se está ligada.
         */
        get: operations["deskListAlertRules"];
        /**
         * Criar ou atualizar uma regra de alerta
         * @description O limiar é informado na UNIDADE DA MÉTRICA: inadimplência de 5% entra como 0.05 (fração), concentração de 60% entra como 60 (percentual). O catálogo em `GET /grid` diz a unidade de cada uma.
         */
        put: operations["deskUpsertAlertRule"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/desk/orgs/{org}/alert-rules/{ruleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remover regra de alerta
         * @description Remove uma regra de alerta. O que já foi registrado no ledger de alertas não muda.
         */
        delete: operations["deskDeleteAlertRule"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/desk/orgs/{org}/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Notas da mesa
         * @description Notas da mesa, mais recente primeiro. `entity_id` recorta por classe ou cedente (CNPJ).
         */
        get: operations["deskListNotes"];
        put?: never;
        /**
         * Escrever nota sobre uma classe ou cedente
         * @description Registra uma nota da mesa sobre uma classe de FIDC ou um cedente, identificado por CNPJ em `entity_id`.
         */
        post: operations["deskCreateNote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/desk/orgs/{org}/notes/{noteId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remover nota
         * @description Remove uma nota da mesa.
         */
        delete: operations["deskDeleteNote"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/desk/orgs/{org}/classes/{cnpj}/terms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Limiares do regulamento de uma classe
         * @description Point-in-time: por padrão devolve só as linhas VIGENTES. Toda linha carrega a procedência (documento, página e trecho) e só `confirmed` alimenta os alertas de covenant.
         */
        get: operations["deskListRegulationTerms"];
        put?: never;
        /**
         * Propor um limiar extraído do regulamento
         * @description O termo nasce SEMPRE como `pending`, mesmo com confiança alta: só a revisão humana (`deskReviewRegulationTerm`) liga o alerta. Valores numéricos seguem a unidade do dado.
         */
        post: operations["deskProposeRegulationTerm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/desk/orgs/{org}/terms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Limiares da mesa inteira
         * @description Fila de revisão cross-classe: todo limiar da mesa, mais novo primeiro, com a classe (`cnpj`) em cada linha. `status=pending` é o que ainda espera revisão humana.
         */
        get: operations["deskListOrgRegulationTerms"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/desk/orgs/{org}/terms/{termId}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirmar ou rejeitar um limiar proposto
         * @description Confirmar FECHA a linha vigente do mesmo (classe, termo) e abre a nova — nada é sobrescrito, para continuar auditável qual limiar valia quando cada alerta disparou.
         */
        post: operations["deskReviewRegulationTerm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    deskGetMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        user_id: string | null;
                        email: string | null;
                        name: string | null;
                        organizations: {
                            org_id: string;
                            org_slug: string;
                            org_name: string;
                            /** @enum {string} */
                            role: "owner" | "admin" | "analyst" | "viewer";
                            member_id: string;
                        }[];
                    };
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type?: string;
                        title: string;
                        status: number;
                        detail?: string;
                        code?: string;
                    };
                };
            };
        };
    };
    deskAcceptInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @description Token do convite, do link recebido por e-mail. */
                    token: string;
                };
            };
        };
        responses: {
            /** @description Assento criado ou reativado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        org_id: string;
                        org_slug: string;
                        member_id: string;
                        role: string;
                    };
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type?: string;
                        title: string;
                        status: number;
                        detail?: string;
                        code?: string;
                    };
                };
            };
        };
    };
    deskGetOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id ou slug da organização (de deskGetMe). */
                org: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        slug: string;
                        name: string;
                        cnpj: string | null;
                        cvm_registration: string | null;
                        status: string;
                    };
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type?: string;
                        title: string;
                        status: number;
                        detail?: string;
                        code?: string;
                    };
                };
            };
        };
    };
    deskUpdateOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id ou slug da organização (de deskGetMe). */
                org: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @description Novo nome da mesa. */
                    name?: string;
                    /** @description Configurações da mesa; `seatAssignment`: automatic ou manual. */
                    settings?: {
                        [key: string]: unknown;
                    };
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        slug: string;
                        name: string;
                        cnpj: string | null;
                        cvm_registration: string | null;
                        status: string;
                    };
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type?: string;
                        title: string;
                        status: number;
                        detail?: string;
                        code?: string;
                    };
                };
            };
        };
    };
    deskGetLicense: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id ou slug da organização (de deskGetMe). */
                org: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        plan: string | null;
                        seats_limit: number;
                        watched_limit: number | null;
                        expires_at: string | null;
                        expired: boolean;
                    };
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type?: string;
                        title: string;
                        status: number;
                        detail?: string;
                        code?: string;
                    };
                };
            };
        };
    };
    deskListMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id ou slug da organização (de deskGetMe). */
                org: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            role: string;
                            display_name: string | null;
                            status: string;
                            created_at: string;
                        }[];
                    };
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type?: string;
                        title: string;
                        status: number;
                        detail?: string;
                        code?: string;
                    };
                };
            };
        };
    };
    deskAssignSeat: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id ou slug da organização (de deskGetMe). */
                org: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @description Id da pessoa na plataforma (já membro da organização). */
                    user_id: string;
                    /**
                     * @description Papel do assento.
                     * @enum {string}
                     */
                    role: "owner" | "admin" | "analyst";
                    /** @description Nome de exibição na mesa (até 120 caracteres). */
                    display_name?: string;
                };
            };
        };
        responses: {
            /** @description Assento criado ou reativado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        role: string;
                        display_name: string | null;
                        status: string;
                        created_at: string;
                    };
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type?: string;
                        title: string;
                        status: number;
                        detail?: string;
                        code?: string;
                    };
                };
            };
        };
    };
    deskUpdateMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id ou slug da organização (de deskGetMe). */
                org: string;
                /** @description Id do assento (de deskListMembers). */
                memberId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /**
                     * @description Novo papel do assento.
                     * @enum {string}
                     */
                    role?: "owner" | "admin" | "analyst";
                    /**
                     * @description active reativa; suspended bloqueia o acesso sem apagar o assento.
                     * @enum {string}
                     */
                    status?: "active" | "suspended";
                    /** @description Novo nome de exibição. */
                    display_name?: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        role: string;
                        display_name: string | null;
                        status: string;
                        created_at: string;
                    };
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type?: string;
                        title: string;
                        status: number;
                        detail?: string;
                        code?: string;
                    };
                };
            };
        };
    };
    deskListInvitations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id ou slug da organização (de deskGetMe). */
                org: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            email: string;
                            role: string;
                            status: string;
                            expires_at: string;
                        }[];
                    };
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type?: string;
                        title: string;
                        status: number;
                        detail?: string;
                        code?: string;
                    };
                };
            };
        };
    };
    deskCreateInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id ou slug da organização (de deskGetMe). */
                org: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /**
                     * Format: email
                     * @description E-mail de quem será convidado.
                     */
                    email: string;
                    /**
                     * @description Papel que a pessoa terá ao aceitar.
                     * @enum {string}
                     */
                    role: "owner" | "admin" | "analyst";
                };
            };
        };
        responses: {
            /** @description Criado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        invitation_id: string;
                        invite_url: string;
                    };
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type?: string;
                        title: string;
                        status: number;
                        detail?: string;
                        code?: string;
                    };
                };
            };
        };
    };
    deskRevokeInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id ou slug da organização (de deskGetMe). */
                org: string;
                /** @description Id do convite (de deskListInvitations). */
                invitationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        revoked: boolean;
                    };
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type?: string;
                        title: string;
                        status: number;
                        detail?: string;
                        code?: string;
                    };
                };
            };
        };
    };
    deskListAudit: {
        parameters: {
            query?: {
                entity_id?: string;
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path: {
                /** @description Id ou slug da organização (de deskGetMe). */
                org: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            action: string;
                            summary: string | null;
                            via: string;
                            actor_member_id: string | null;
                            actor_display_name: string | null;
                            entity_type: string | null;
                            entity_id: string | null;
                            created_at: string;
                        }[];
                        meta: {
                            next_cursor: string | null;
                            count: number;
                        };
                    };
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type?: string;
                        title: string;
                        status: number;
                        detail?: string;
                        code?: string;
                    };
                };
            };
        };
    };
    deskListWatchlists: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id ou slug da organização (de deskGetMe). */
                org: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            slug: string;
                            name: string;
                            description: string | null;
                            kind: string;
                            item_count: number;
                        }[];
                    };
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type?: string;
                        title: string;
                        status: number;
                        detail?: string;
                        code?: string;
                    };
                };
            };
        };
    };
    deskCreateWatchlist: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id ou slug da organização (de deskGetMe). */
                org: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @description Nome da watchlist. */
                    name: string;
                    /** @description Slug estável para a URL; derivado do nome quando omitido. */
                    slug?: string;
                    /** @description Descrição livre. */
                    description?: string | null;
                    /**
                     * @description book = o que a casa gere ou originou; market = o que ela observa (default).
                     * @enum {string}
                     */
                    kind?: "book" | "market";
                };
            };
        };
        responses: {
            /** @description Criado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        slug: string;
                        name: string;
                        description: string | null;
                        kind: string;
                        item_count: number;
                    };
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type?: string;
                        title: string;
                        status: number;
                        detail?: string;
                        code?: string;
                    };
                };
            };
        };
    };
    deskDeleteWatchlist: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id ou slug da organização (de deskGetMe). */
                org: string;
                /** @description Id ou slug da watchlist (de deskListWatchlists). */
                list: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        deleted: boolean;
                    };
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type?: string;
                        title: string;
                        status: number;
                        detail?: string;
                        code?: string;
                    };
                };
            };
        };
    };
    deskListWatchlistItems: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id ou slug da organização (de deskGetMe). */
                org: string;
                /** @description Id ou slug da watchlist (de deskListWatchlists). */
                list: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            cnpj: string;
                            entity_kind: string;
                            label: string | null;
                            relation: string;
                            position: number;
                        }[];
                    };
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type?: string;
                        title: string;
                        status: number;
                        detail?: string;
                        code?: string;
                    };
                };
            };
        };
    };
    deskAddWatchlistItems: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id ou slug da organização (de deskGetMe). */
                org: string;
                /** @description Id ou slug da watchlist (de deskListWatchlists). */
                list: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @description Posições a incluir na watchlist (1–500), identificadas por CNPJ. */
                    items: {
                        /** @description CNPJ da classe de FIDC ou do cedente, com ou sem pontuação. */
                        cnpj: string;
                        /** @description Apelido da posição na mesa. */
                        label?: string | null;
                        /**
                         * @description fidc_class (default) ou originator (cedente).
                         * @enum {string}
                         */
                        entity_kind?: "fidc_class" | "originator";
                        /**
                         * @description O que a classe é PARA A MESA. `own`: a casa gere ou originou — quebra de limite aqui é operacional. `tracked` (default): exposição, avaliação ou comparação.
                         * @enum {string}
                         */
                        relation?: "own" | "tracked";
                    }[];
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        added: number;
                        skipped: number;
                    };
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type?: string;
                        title: string;
                        status: number;
                        detail?: string;
                        code?: string;
                    };
                };
            };
        };
    };
    deskRemoveWatchlistItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id ou slug da organização (de deskGetMe). */
                org: string;
                /** @description Id ou slug da watchlist (de deskListWatchlists). */
                list: string;
                /** @description CNPJ da classe de FIDC ou do cedente, 14 dígitos. */
                cnpj: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        removed: boolean;
                    };
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type?: string;
                        title: string;
                        status: number;
                        detail?: string;
                        code?: string;
                    };
                };
            };
        };
    };
    deskGetWatchlistBoard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id ou slug da organização (de deskGetMe). */
                org: string;
                /** @description Id ou slug da watchlist (de deskListWatchlists). */
                list: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        watchlist: {
                            id: string;
                            slug: string;
                            name: string;
                            kind: string;
                        };
                        /** @description Competência mais recente do informe no mercado (YYYY-MM-DD). */
                        latest_competence: string | null;
                        columns: {
                            metric: string;
                            label: string;
                            unit: string;
                            help: string;
                        }[];
                        rows: {
                            cnpj: string;
                            entity_kind: string;
                            /** @description `own` (a casa gere/originou) ou `tracked`. */
                            relation: string;
                            label: string | null;
                            name: string | null;
                            reference_date: string | null;
                            /** @description True quando o informe não conhece este CNPJ — diferente de conhecer e estar atrasado. */
                            unknown: boolean;
                            cells: {
                                metric: string;
                                value: number | null;
                                unit: string;
                            }[];
                        }[];
                    };
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type?: string;
                        title: string;
                        status: number;
                        detail?: string;
                        code?: string;
                    };
                };
            };
        };
    };
    deskGetGrid: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id ou slug da organização (de deskGetMe). */
                org: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        columns: {
                            metric: string;
                            position: number;
                        }[];
                        catalog: {
                            metric: string;
                            label: string;
                            unit: string;
                            help: string;
                        }[];
                    };
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type?: string;
                        title: string;
                        status: number;
                        detail?: string;
                        code?: string;
                    };
                };
            };
        };
    };
    deskSetGrid: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id ou slug da organização (de deskGetMe). */
                org: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @description Métricas do catálogo de deskGetGrid, na ordem das colunas (até 30). */
                    metrics: string[];
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        columns: string[];
                    };
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type?: string;
                        title: string;
                        status: number;
                        detail?: string;
                        code?: string;
                    };
                };
            };
        };
    };
    deskListAlerts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id ou slug da organização (de deskGetMe). */
                org: string;
                /** @description Id ou slug da watchlist (de deskListWatchlists). */
                list: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            key: string;
                            cnpj: string;
                            name: string | null;
                            /** @enum {string} */
                            source: "covenant" | "rule" | "reporting";
                            /** @enum {string} */
                            severity: "info" | "attention" | "critical";
                            metric: string;
                            value: number | null;
                            threshold: number | null;
                            /** @description Quanto falta para cruzar o limiar, na unidade da métrica. Negativo = já cruzou. */
                            distance: number | null;
                            reference_date: string | null;
                            title: string;
                            /** @description Procedência do limiar no regulamento. Presente só quando a origem é covenant. */
                            evidence: {
                                doc_id: string | null;
                                page: number | null;
                                quote: string | null;
                            } | null;
                            /** @enum {string} */
                            status: "open" | "acknowledged" | "muted";
                            /** @description Primeira vez que este alerta foi observado (ledger append-only). */
                            first_detected_at?: string | null;
                        }[];
                        meta: {
                            count: number;
                        };
                    };
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type?: string;
                        title: string;
                        status: number;
                        detail?: string;
                        code?: string;
                    };
                };
            };
        };
    };
    deskListAlertHistory: {
        parameters: {
            query?: {
                cnpj?: string;
                source?: "covenant" | "rule" | "reporting";
                since?: string;
                limit?: number;
            };
            header?: never;
            path: {
                /** @description Id ou slug da organização (de deskGetMe). */
                org: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            alert_key: string;
                            cnpj: string;
                            source: string;
                            severity: string;
                            metric: string;
                            value: number | null;
                            threshold: number | null;
                            distance: number | null;
                            reference_date: string | null;
                            title: string;
                            detected_at: string;
                        }[];
                        meta: {
                            count: number;
                        };
                    };
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type?: string;
                        title: string;
                        status: number;
                        detail?: string;
                        code?: string;
                    };
                };
            };
        };
    };
    deskAcknowledgeAlert: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id ou slug da organização (de deskGetMe). */
                org: string;
                /** @description Chave do alerta (de deskListAlerts). */
                key: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /**
                     * @description acknowledged = visto (default); muted = silenciado nesta competência.
                     * @default acknowledged
                     * @enum {string}
                     */
                    status?: "acknowledged" | "muted";
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        key: string;
                        status: string;
                    };
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type?: string;
                        title: string;
                        status: number;
                        detail?: string;
                        code?: string;
                    };
                };
            };
        };
    };
    deskListAlertRules: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id ou slug da organização (de deskGetMe). */
                org: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            metric: string;
                            comparator: string;
                            threshold: number;
                            severity: string;
                            enabled: boolean;
                        }[];
                    };
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type?: string;
                        title: string;
                        status: number;
                        detail?: string;
                        code?: string;
                    };
                };
            };
        };
    };
    deskUpsertAlertRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id ou slug da organização (de deskGetMe). */
                org: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @description Métrica do catálogo de deskGetGrid. */
                    metric: string;
                    /**
                     * @description gt dispara acima do limiar; lt, abaixo.
                     * @enum {string}
                     */
                    comparator: "gt" | "lt";
                    /** @description Limiar na UNIDADE da métrica (fração para inadimplência: 0.05 = 5%; percentual para concentração: 60 = 60%). */
                    threshold: number;
                    /**
                     * @description Severidade do alerta gerado (default attention).
                     * @enum {string}
                     */
                    severity?: "info" | "attention" | "critical";
                    /** @description false desliga a regra sem apagá-la. */
                    enabled?: boolean;
                };
            };
        };
        responses: {
            /** @description Criado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        metric: string;
                        comparator: string;
                        threshold: number;
                        severity: string;
                        enabled: boolean;
                    };
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type?: string;
                        title: string;
                        status: number;
                        detail?: string;
                        code?: string;
                    };
                };
            };
        };
    };
    deskDeleteAlertRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id ou slug da organização (de deskGetMe). */
                org: string;
                /** @description Id da regra (de deskListAlertRules). */
                ruleId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        deleted: boolean;
                    };
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type?: string;
                        title: string;
                        status: number;
                        detail?: string;
                        code?: string;
                    };
                };
            };
        };
    };
    deskListNotes: {
        parameters: {
            query?: {
                entity_id?: string;
                limit?: number;
            };
            header?: never;
            path: {
                /** @description Id ou slug da organização (de deskGetMe). */
                org: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            entity_kind: string;
                            entity_id: string;
                            body: string;
                            author_member_id: string | null;
                            author_name: string | null;
                            created_at: string;
                            updated_at: string;
                        }[];
                    };
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type?: string;
                        title: string;
                        status: number;
                        detail?: string;
                        code?: string;
                    };
                };
            };
        };
    };
    deskCreateNote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id ou slug da organização (de deskGetMe). */
                org: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @description CNPJ da classe de FIDC ou do cedente. */
                    entity_id: string;
                    /**
                     * @description fidc_class (default) ou originator.
                     * @enum {string}
                     */
                    entity_kind?: "fidc_class" | "originator";
                    /** @description Texto da nota (até 10.000 caracteres). */
                    body: string;
                };
            };
        };
        responses: {
            /** @description Criado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                    };
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type?: string;
                        title: string;
                        status: number;
                        detail?: string;
                        code?: string;
                    };
                };
            };
        };
    };
    deskDeleteNote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id ou slug da organização (de deskGetMe). */
                org: string;
                /** @description Id da nota (de deskListNotes). */
                noteId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        deleted: boolean;
                    };
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type?: string;
                        title: string;
                        status: number;
                        detail?: string;
                        code?: string;
                    };
                };
            };
        };
    };
    deskListRegulationTerms: {
        parameters: {
            query?: {
                include_history?: boolean;
                status?: "pending" | "confirmed" | "rejected";
            };
            header?: never;
            path: {
                /** @description Id ou slug da organização (de deskGetMe). */
                org: string;
                /** @description CNPJ da classe de FIDC ou do cedente, 14 dígitos. */
                cnpj: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            cnpj: string;
                            term: string;
                            label: string;
                            value_num: number | null;
                            value_text: string | null;
                            unit: string | null;
                            doc_id: string | null;
                            doc_page: number | null;
                            quote: string | null;
                            confidence: number | null;
                            /** @enum {string} */
                            status: "pending" | "confirmed" | "rejected";
                            valid_from: string;
                            valid_to: string | null;
                        }[];
                        meta: {
                            terms: string[];
                        };
                    };
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type?: string;
                        title: string;
                        status: number;
                        detail?: string;
                        code?: string;
                    };
                };
            };
        };
    };
    deskProposeRegulationTerm: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id ou slug da organização (de deskGetMe). */
                org: string;
                /** @description CNPJ da classe de FIDC ou do cedente, 14 dígitos. */
                cnpj: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /**
                     * @description Qual limiar do regulamento (chave do vocabulário fechado).
                     * @enum {string}
                     */
                    term: "subordinacao_minima" | "inadimplencia_max" | "concentracao_cedente_max" | "revolvente" | "coobrigacao_cedente" | "taxa_administracao" | "taxa_performance" | "benchmark_alvo";
                    /** @description Valor numérico na unidade declarada (fração para razão; BRL; % a.a.). */
                    value_num?: number | null;
                    /** @description Valor em texto quando o limiar não é numérico. */
                    value_text?: string | null;
                    /**
                     * @description Unidade do valor: ratio, brl, percent_year ou text.
                     * @enum {string|null}
                     */
                    unit?: "ratio" | "brl" | "percent_year" | "text" | null;
                    /** @description Documento de onde o limiar foi lido (protocolo). */
                    doc_id?: string | null;
                    /** @description Página do documento. */
                    doc_page?: number | null;
                    /** @description Trecho literal que sustenta o limiar. */
                    quote?: string | null;
                    /** @description Confiança da extração, de 0 a 1. */
                    confidence?: number | null;
                };
            };
        };
        responses: {
            /** @description Criado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        cnpj: string;
                        term: string;
                        label: string;
                        value_num: number | null;
                        value_text: string | null;
                        unit: string | null;
                        doc_id: string | null;
                        doc_page: number | null;
                        quote: string | null;
                        confidence: number | null;
                        /** @enum {string} */
                        status: "pending" | "confirmed" | "rejected";
                        valid_from: string;
                        valid_to: string | null;
                    };
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type?: string;
                        title: string;
                        status: number;
                        detail?: string;
                        code?: string;
                    };
                };
            };
        };
    };
    deskListOrgRegulationTerms: {
        parameters: {
            query?: {
                status?: "pending" | "confirmed" | "rejected";
                limit?: number;
            };
            header?: never;
            path: {
                /** @description Id ou slug da organização (de deskGetMe). */
                org: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            cnpj: string;
                            term: string;
                            label: string;
                            value_num: number | null;
                            value_text: string | null;
                            unit: string | null;
                            doc_id: string | null;
                            doc_page: number | null;
                            quote: string | null;
                            confidence: number | null;
                            /** @enum {string} */
                            status: "pending" | "confirmed" | "rejected";
                            valid_from: string;
                            valid_to: string | null;
                        }[];
                        meta: {
                            count: number;
                        };
                    };
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type?: string;
                        title: string;
                        status: number;
                        detail?: string;
                        code?: string;
                    };
                };
            };
        };
    };
    deskReviewRegulationTerm: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id ou slug da organização (de deskGetMe). */
                org: string;
                /** @description Id do limiar (de deskListOrgRegulationTerms). */
                termId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /**
                     * @description confirmed liga o limiar aos alertas; rejected descarta a proposta.
                     * @enum {string}
                     */
                    decision: "confirmed" | "rejected";
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        cnpj: string;
                        term: string;
                        label: string;
                        value_num: number | null;
                        value_text: string | null;
                        unit: string | null;
                        doc_id: string | null;
                        doc_page: number | null;
                        quote: string | null;
                        confidence: number | null;
                        /** @enum {string} */
                        status: "pending" | "confirmed" | "rejected";
                        valid_from: string;
                        valid_to: string | null;
                    };
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type?: string;
                        title: string;
                        status: number;
                        detail?: string;
                        code?: string;
                    };
                };
            };
        };
    };
}
