-- Demonstrações limpas por (cnpj, trimestre): TTM + balanço + derivados.
-- Base de serving p/ GET /v1/companies/{id}/statements.
select
    cnpj,
    cd_cvm,
    company_name,
    ref_date,
    scope,
    quarters_available,
    is_latest,
    revenue_ttm,
    gross_profit_ttm,
    ebit_ttm,
    ebitda_ttm,
    net_income_ttm,
    ocf_ttm,
    fcf_ttm,
    dna_ttm,
    capex_ttm,
    total_assets,
    current_assets,
    cash,
    st_investments,
    current_liabilities,
    noncurrent_liabilities,
    st_debt,
    lt_debt,
    gross_debt,
    net_debt,
    equity,
    working_capital,
    net_current_assets,
    invested_capital,
    nopat_ttm
from {{ ref('int_fund__ttm') }}
