/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/portfolio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sua carteira (consolidada)
         * @description Retorna a carteira consolidada do dono da chave de API: patrimônio, total investido, P&L realizado e não-realizado, variação do dia, composição por classe, TODAS as posições (`positions`, maiores primeiro) e quebra por carteira. Exige uma chave de API por usuário (crie em https://databolsa.com/conta).
         */
        get: operations["getPortfolio"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/portfolio/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Histórico mensal consolidado
         * @description Série mensal do patrimônio consolidado do dono da chave: valor de mercado, aporte acumulado, proventos recebidos e resultado realizado, mês a mês. Exclui carteiras marcadas como simulação.
         */
        get: operations["getPortfolioHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/portfolios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Suas carteiras
         * @description Lista as carteiras do dono da chave (id, nome, nº de linhas de ativo no ledger, flag de simulação). Use o `id` nas demais operações de carteira.
         */
        get: operations["listPortfolios"];
        put?: never;
        /**
         * Criar carteira
         * @description CRIA uma carteira REAL na conta do dono da chave. O número de carteiras é limitado pelo plano (resposta 402 quando o teto é atingido). Nome único por conta (409 em duplicidade).
         */
        post: operations["createPortfolio"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/portfolios/import-template": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Template CSV de import manual
         * @description Baixa o template CSV de preenchimento manual (colunas: ticker, operacao, data, quantidade, preco) aceito pelo import de planilha.
         */
        get: operations["getPortfolioImportTemplate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/portfolios/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Detalhe de uma carteira
         * @description Retorna posições calculadas, totais, proventos, resultado e retornos. Por padrão, `holdings` inclui apenas posições abertas e watchlist, sem séries mensais ou transações. Use `include` para adicionar essas camadas, ou `listPortfolioTransactions` para o ledger de um ativo.
         */
        get: operations["getPortfolioDetail"];
        put?: never;
        post?: never;
        /**
         * Apagar carteira
         * @description APAGA a carteira REAL do dono da chave, com TODOS os ativos e transações (cascata, irreversível). Confirme com o usuário antes de chamar.
         */
        delete: operations["deletePortfolio"];
        options?: never;
        head?: never;
        /**
         * Editar carteira
         * @description ALTERA a carteira REAL do dono da chave: renomeia (`name`), muda a visibilidade (`visibility`) e/ou marca como simulação (`exclude_from_consolidated`, fora do consolidado). Informe ao menos um campo.
         */
        patch: operations["updatePortfolio"];
        trace?: never;
    };
    "/v1/portfolios/{id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Histórico mensal de uma carteira
         * @description Série mensal (patrimônio, aporte, proventos, realizado) de UMA carteira específica, com o TWR time-weighted. A xirr money-weighted da mesma carteira está em getPortfolioDetail (`returns`).
         */
        get: operations["getPortfolioHistoryById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/portfolios/{id}/xray": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Raio-X de concentração da carteira
         * @description Distribui posições abertas por classe, setor, indexador e moeda, e lista as dez maiores. `flags` registra limites de concentração sem emitir recomendação. Percentuais de `by_indexer` usam apenas a renda fixa; os demais usam a carteira. Posições sem valor são ignoradas e contadas em `meta.unpriced_ignored`. Valores estão em reais e percentuais de 0 a 100.
         */
        get: operations["getPortfolioXray"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/portfolios/{id}/costs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Raio-X de custos recorrentes da carteira
         * @description Estima custos anuais observáveis de posições abertas: administração de fundos, custódia do Tesouro e diferença de renda fixa bancária tributável para 100% do CDI. `items` traz destinatário, referência e excesso; `by_recipient` e `totals` agregam. Custos sem base pública ficam em `not_estimated`, sem valor inferido. `flags` descreve fatos, não recomendações.
         */
        get: operations["getPortfolioCosts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/portfolios/{id}/look-through": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Exposição efetiva (abre as posições em fundos)
         * @description Abre posições em fundos pela última carteira mensal divulgada e agrega exposição direta e indireta por ativo, até dois níveis. `via` mostra os fundos intermediários; `funds_opened` informa competência, cobertura e denominador, e `not_opened` lista fundos sem dados. Como as carteiras são defasadas e parciais, a exposição indireta é um piso. Valores estão em reais e percentuais de 0 a 100.
         */
        get: operations["getPortfolioLookThrough"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/portfolios/{id}/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Adicionar ativo à carteira
         * @description Adiciona um ativo de forma idempotente; sem transações, ele funciona como watchlist. Prefira `entity_id`. Alternativamente, use tipo e símbolo: nome oficial para Tesouro, CNPJ da classe para fundo, código do papel para debênture e código de balcão para outras rendas fixas. A marcação usa negócio recente quando disponível; caso contrário, accrual.
         */
        post: operations["addPortfolioAsset"];
        /**
         * Remover ativo da carteira
         * @description REMOVE um ativo da carteira REAL do dono da chave, APAGANDO o ledger de transações dele nesta carteira (cascata, irreversível). Confirme com o usuário antes de chamar.
         */
        delete: operations["removePortfolioAsset"];
        options?: never;
        head?: never;
        /**
         * Taxa contratada de renda fixa
         * @description DEFINE a taxa contratada de uma posição de renda fixa (para o cálculo de rendimento): `rf_indexer` (cdi = % do CDI, prefixado = % a.a., ipca = IPCA + % a.a.) e `rf_rate`. Use `rf_indexer: none` para limpar.
         */
        patch: operations["updatePortfolioAsset"];
        trace?: never;
    };
    "/v1/portfolios/{id}/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ledger de um ativo
         * @description Lista as transações (compras, vendas, splits, ajustes) de um ativo da carteira, em ordem cronológica.
         */
        get: operations["listPortfolioTransactions"];
        put?: never;
        /**
         * Lançar transação
         * @description Lança uma transação na carteira real do dono da chave; ativo ausente é adicionado automaticamente. buy/sell exigem `quantity`; `price` é opcional; split usa `ratio` (2 = 2:1). Confirme os valores com o usuário.
         */
        post: operations["addPortfolioTransaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/portfolios/{id}/transactions/{txId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remover transação
         * @description REMOVE uma transação do ledger da carteira REAL do dono da chave (irreversível). Confirme com o usuário antes de chamar.
         */
        delete: operations["deletePortfolioTransaction"];
        options?: never;
        head?: never;
        /**
         * Editar transação
         * @description ALTERA uma transação existente da carteira REAL do dono da chave (patch parcial: informe só os campos a mudar). Confirme com o usuário antes de chamar.
         */
        patch: operations["updatePortfolioTransaction"];
        trace?: never;
    };
    "/v1/portfolios/{id}/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Histórico de imports
         * @description Lista os imports já feitos nesta carteira (arquivo, fonte, data e resumo persistido).
         */
        get: operations["listPortfolioImports"];
        put?: never;
        /**
         * Importar planilha (B3 ou template manual)
         * @description Importa uma planilha para a carteira real do dono da chave: Negociação ou Movimentação da B3 (.xlsx) ou o template manual (.csv/.xlsx), com formato detectado automaticamente. Envie em `content_base64` (máximo 8 MB). Idempotente: reenviar o mesmo arquivo não duplica. A resposta resume importadas, duplicadas e ignoradas, com avisos.
         */
        post: operations["importPortfolioFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/portfolios/{id}/imports/{importId}/rows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Linhas de um import
         * @description Drill-down de um import: cada linha do arquivo com status (imported, ignored, duplicate, error) e motivo.
         */
        get: operations["listPortfolioImportRows"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/portfolios/{id}/reconcile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reconciliar posição à B3
         * @description Ajusta a posição calculada de um ativo à quantidade declarada pela B3 (`target_qty` em `as_of`) com um lançamento idempotente, para eventos que não vieram no extrato. Confirme a quantidade com o usuário antes de chamar.
         */
        post: operations["reconcilePortfolioAsset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/suitability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Seu perfil de investidor
         * @description Retorna o perfil de investidor (suitability) do dono da chave: nível (Conservador/Moderado/Arrojado), a posição na régua 0–100 (não é uma nota) e as respostas do questionário. `profile` é nulo se o usuário ainda não definiu o perfil.
         */
        get: operations["getSuitability"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SuitabilityProfile: {
            /** @enum {string} */
            level: "Conservador" | "Moderado" | "Arrojado";
            /** @description Posição na régua 0–100 (Conservador→Arrojado), não uma nota. */
            score: number;
            answers: {
                q: string;
                a: string;
            }[];
            updatedAt: string;
        };
        SuitabilityEnvelope: {
            profile: components["schemas"]["SuitabilityProfile"] | null;
        };
        /** @description Posição computada da carteira (snake_case, como todo o /v1). `asset_type` e `transactions[].trade_date` são os MESMOS campos do ledger (listPortfolioTransactions). Valores monetários sempre em BRL; ativos em moeda estrangeira (asset_type=us) expõem também currency, price_native (US$), fx_rate e o bloco `native` com a MESMA posição em dólar (custo, valor de mercado e P&L). */
        PortfolioHolding: {
            symbol: string;
            /** @description stock | fii | etf | bdr | index | tesouro | crypto | option | renda_fixa | debenture | fund | us. `debenture` = crédito privado com catálogo próprio (símbolo = código do papel); `fund` = fundo CVM 175 (símbolo = CNPJ da classe, 14 dígitos). */
            asset_type: string;
            name?: string;
            qty: number;
            /** @description Preço médio de custo (null = custo desconhecido/watchlist). */
            avg_price?: number | null;
            invested_cost?: number | null;
            /** @description true quando todos os buy/sell têm preço → P&L confiável. */
            cost_basis_known?: boolean;
            /** @description Cotação atual em BRL (null = sem cotação). */
            price?: number | null;
            /** @description Variação do dia em BRL. Em posição estrangeira é o COMPOSTO do retorno do ativo com o do câmbio, (1+ativo)×(1+câmbio)−1 — a variação só do ativo, na moeda dele, está em native.change_pct. */
            change_pct?: number | null;
            market_value?: number | null;
            /** @description Resultado não-realizado em R$. Com valuation=accrual (renda fixa privada) é RENDIMENTO acruado pela taxa contratada, não marcação a mercado. */
            unrealized_pl?: number | null;
            /** @description Percentual sobre o custo. null quando o percentual é indefinido — veja unrealized_pct_reason. */
            unrealized_pct?: number | null;
            /**
             * @description Por que unrealized_pct é null numa posição aberta e valorada: zero_cost = custo abaixo de um centavo (resíduo de fusão/bonificação — o percentual é indefinido, não 0 nem centenas de por cento); cost_unknown = há buy/sell sem preço no ledger. null = percentual definido.
             * @enum {string|null}
             */
            unrealized_pct_reason?: "zero_cost" | "cost_unknown" | null;
            /**
             * @description Como a posição foi valorada (linhagem do número): market = cotação (para debênture, o PU do secundário com no máx. ~30 dias); accrual = renda fixa/debênture acruada pela taxa contratada (contrato do usuário ou pré-preenchido do catálogo — veja meta.rf.source); cost = sem cotação, marcada pelo custo remanescente; null = sem valor de mercado.
             * @enum {string|null}
             */
            valuation?: "market" | "accrual" | "cost" | null;
            realized_pl?: number | null;
            /** @description 'AAAA-MM' → R$ realizado no mês. Só presente com `include=monthly`. */
            realized_by_month?: {
                [key: string]: number;
            };
            /** @description Proventos recebidos acumulados (R$). */
            income_received?: number;
            /** @description 'AAAA-MM' → R$ de proventos no mês. Só presente com `include=monthly`. */
            income_by_month?: {
                [key: string]: number;
            };
            weight_pct?: number | null;
            day_change_brl?: number | null;
            /** @description Data da 1ª transação (AAAA-MM-DD). */
            added_at?: string | null;
            /** @description Nº de transações da posição. */
            tx_count?: number;
            /** @description qty = 0 com transações (posição encerrada). */
            closed?: boolean;
            /** @description Entrada sem nenhuma transação (radar). */
            is_watchlist?: boolean;
            priced?: boolean;
            /** @description Ticker vigente quando o papel foi renomeado/incorporado. */
            renamed_to?: string | null;
            /** @description Tickers antigos fundidos nesta posição por sucessão (ex.: ['BCFF11'] num holding BTHF11). O ledger em `transactions` já inclui as transações dos predecessores. null = nenhum. */
            merged_from?: string[] | null;
            /** @description Moeda nativa de negociação (BRL | USD). */
            currency?: string;
            /** @description Cotação na moeda nativa quando ≠ BRL. */
            price_native?: number | null;
            /** @description Câmbio usado na marcação (price = price_native × fx_rate). */
            fx_rate?: number | null;
            native?: components["schemas"]["PortfolioHoldingNative"];
            /** @description Id do ativo no ledger (correlaciona com /assets e /transactions). */
            asset_id?: string | null;
            /** @description portfolio_assets.meta (ex.: { rf: { indexer, rate } }). */
            meta?: unknown;
            /** @description Ledger da posição, ordenado por trade_date. Só presente com `include=transactions`; o mesmo dado, por ativo, está em listPortfolioTransactions. */
            transactions?: components["schemas"]["PortfolioTransaction"][];
        };
        /**
         * @description A MESMA posição na moeda em que ela é negociada, quando não é o real (hoje, asset_type=us em USD). null para o que negocia em BRL.
         *
         *     NÃO é o bloco em BRL dividido por fx_rate: é o mesmo cálculo rodado sobre o ledger cru, porque cada compra foi convertida pela PTAX da SUA data. Por isso invested_cost é o que se pagou em dólar e unrealized_pct é o retorno do ATIVO, enquanto o unrealized_pct em BRL embute também a variação do câmbio no período. Os dois estão certos e respondem a perguntas diferentes.
         *
         *     Não repete qty (idêntico), weight_pct (adimensional) nem day_change_brl (escopo BRL).
         */
        PortfolioHoldingNative: {
            /** @description Moeda da negociação (ex.: USD). */
            currency: string;
            /** @description Preço médio pago na moeda nativa. */
            avg_price?: number | null;
            invested_cost?: number | null;
            /** @description Pode divergir do cost_basis_known em BRL: numa data sem PTAX o custo em real fica desconhecido enquanto o em dólar segue conhecido. */
            cost_basis_known?: boolean;
            /** @description Cotação na moeda nativa (= price_native). */
            price?: number | null;
            /** @description Variação do dia do ativo, sem o câmbio. */
            change_pct?: number | null;
            market_value?: number | null;
            unrealized_pl?: number | null;
            /** @description Retorno do ativo, sem o efeito do câmbio. */
            unrealized_pct?: number | null;
            realized_pl?: number | null;
            income_received?: number;
        } | null;
        /**
         * @description Câmbio USD/BRL aplicado na marcação a mercado das posições estrangeiras desta carteira. Publicado para a conversão ser conferível: os totais da carteira são BRL e dependem desta taxa. null quando a carteira não tem ativo em moeda estrangeira.
         *
         *     Atenção: esta é a taxa SPOT, usada só na marcação. O custo de cada compra foi convertido pela PTAX da data do trade, então invested_cost ÷ usd_brl não devolve o custo em dólar — para isso use holdings[].native.invested_cost.
         */
        PortfolioFx: {
            /** @description Reais por dólar. */
            usd_brl: number;
            /** @description Timestamp da taxa. Com source=usdt é ISO 8601 completo (o par é atualizado a cada minuto); com source=bcb é a data do pregão (AAAA-MM-DD). */
            as_of: string;
            /**
             * @description usdt = par USDT/BRL, atualizado 24/7 e fresco mesmo fora do horário de pregão; bcb = PTAX de venda do BCB (série 1), último fechamento — o fallback.
             * @enum {string}
             */
            source: "usdt" | "bcb";
            /** @description Variação da PRÓPRIA fonte acima (24h do par × pregão a pregão da PTAX), nunca uma mistura das duas. Compõe change_pct das posições estrangeiras. */
            change_pct?: number | null;
        } | null;
        PortfolioByCarteira: {
            name: string;
            patrimonio: number;
            unrealized_pct: number;
            /** @description Posições com quantidade > 0 nesta carteira. */
            open_positions: number;
            /** @description Entradas sem nenhuma transação (radar) nesta carteira. */
            watchlist_entries: number;
        };
        PortfolioListItem: {
            id: string;
            name: string;
            /** @description Nº de LINHAS DE ATIVO no ledger da carteira. Inclui posições já encerradas e tickers predecessores fundidos por sucessão, que não têm holding próprio — por isso é ≥ holdings_count do detalhe, que por sua vez é ≥ open_positions. */
            ledger_assets?: number;
            /** Format: date-time */
            created_at?: string;
            /** @description true = carteira de simulação. */
            exclude_from_consolidated?: boolean;
        };
        /** @description Carteira computada: posições derivadas do ledger + métricas agregadas (snake_case). */
        PortfolioDetail: {
            id?: string;
            name?: string;
            visibility?: string;
            created_at?: string | null;
            /** @description true = carteira de simulação. */
            exclude_from_consolidated?: boolean;
            /** @description Linhas devolvidas em holdings[]. Default: abertas + watchlist; com `include=closed` soma também as encerradas. */
            holdings_count?: number;
            /** @description Posições com quantidade > 0. */
            open_positions?: number;
            /** @description Posições zeradas por venda (qty = 0 com transações). */
            closed_positions?: number;
            /** @description Entradas sem nenhuma transação (radar). */
            watchlist_entries?: number;
            /** @description Tickers predecessores fundidos nas posições por sucessão. Contam em ledger_assets (listPortfolios) e não em holdings_count — é a diferença entre as duas contagens. */
            merged_assets?: number;
            patrimonio?: number;
            invested?: number;
            unrealized_pl?: number;
            unrealized_pct?: number;
            realized_pl?: number;
            realized_by_month?: {
                [key: string]: number;
            };
            income_received?: number;
            income_by_month?: {
                [key: string]: number;
            };
            /** @description unrealized_pl + realized_pl. */
            total_pl?: number;
            /** @description XIRR (TIR anualizada, money-weighted): o retorno REAL do investidor sobre os fluxos datados (aportes/resgates/proventos) + patrimônio a mercado como valor terminal. Decimal a.a. (0,1423 = 14,23%). null quando custo desconhecido, fluxo sem TIR definível ou implausível (> +300% a.a., artefato de giro/curto prazo → use o twr). Mesmo valor de returns.xirr, onde ele aparece ao lado do time-weighted. */
            xirr?: number | null;
            returns?: components["schemas"]["PortfolioReturns"];
            day_change_brl?: number;
            day_change_pct?: number;
            /** @description Resumo humano, ex.: '3 ações · 2 FIIs'. */
            kind_mix?: string;
            is_watchlist?: boolean;
            any_unpriced?: boolean;
            any_cost_unknown?: boolean;
            fx?: components["schemas"]["PortfolioFx"];
            /** @description Posições com qty, preço médio, valor de mercado, P&L, proventos e peso. Default compacto: só abertas + watchlist (posições encerradas exigem `include=closed`) e sem as séries mensais por posição (`include=monthly`). */
            holdings?: components["schemas"]["PortfolioHolding"][];
        };
        /** @description Transação do ledger. É o MESMO shape das transações embutidas em PortfolioHolding.transactions. */
        PortfolioTransaction: {
            id: string;
            /** @description buy | sell | split | adjust */
            kind: string;
            /** @description AAAA-MM-DD */
            trade_date: string;
            quantity: number;
            /** @description Preço unitário (null = custo desconhecido). */
            price?: number | null;
            fees?: number;
            /** @description Fator do split (só kind=split). */
            ratio?: number | null;
            /** @description Moeda de price/fees DESTA linha. O ledger é devolvido CRU, como lançado: o de um ativo americano vem em USD e NÃO passou pela conversão que as posições sofrem. Sem ler este campo o consumidor assume real e exibe uma compra de US$ 178,40 como R$ 178,40. */
            currency?: string;
            note?: string | null;
            /** @description Subtipo do evento societário de origem quando a transação veio de evento (import da Movimentação B3): split | bonus | incorporation | subscription | fraction. null = lançamento comum. */
            event_kind?: string | null;
        };
        /** @description TWR (time-weighted return) derivado da série mensal — neutraliza o efeito do timing dos aportes, o número comparável a benchmark (CDI/IBOV/IPCA). null quando não há período válido. */
        PortfolioTwr: {
            /** @description Retorno acumulado na janela (decimal; 0,25 = +25%). */
            cumulative?: number;
            /** @description Equivalente anualizado (decimal). */
            annualized?: number | null;
            /** @description Meses na grade. */
            months?: number;
        } | null;
        /** @description As DUAS medidas de retorno da carteira no mesmo objeto. Elas divergem sempre que os aportes não são uniformes — é esperado, não é erro, e `explain` diz isso em uma linha. */
        PortfolioReturns: {
            /** @description Money-weighted anualizada (decimal a.a.). */
            xirr?: number | null;
            twr?: components["schemas"]["PortfolioTwr"];
            /** @description Nota curta sobre a diferença entre as duas medidas. */
            explain?: string;
        };
        PortfolioHistoryResponse: {
            data: Record<string, never>[];
            meta: {
                /** @description Sempre null: resposta em página única. */
                next_cursor: string | null;
                /** @description Itens nesta página. */
                count: number;
                twr?: components["schemas"]["PortfolioTwr"];
            };
        };
        /** @description Histórico de UMA carteira: a série mensal em `data`, o TWR e a nota que o separa da xirr do detalhe em `meta`. */
        PortfolioHistoryDetailResponse: {
            data: Record<string, never>[];
            meta: {
                /** @description Sempre null: resposta em página única. */
                next_cursor: string | null;
                /** @description Itens nesta página. */
                count: number;
                twr?: components["schemas"]["PortfolioTwr"];
                /** @description Por que o twr daqui difere da xirr do detalhe da carteira (time-weighted × money-weighted). */
                returns_explain?: string;
            };
        };
        PortfolioXraySlice: {
            /** @description Valor cru em BRL. */
            value_brl: number;
            /** @description Percentual 0-100 (em by_indexer, sobre o total de renda fixa). */
            pct: number;
        };
        /** @description Raio-X de concentração: agregações determinísticas + flags factuais. Só posições abertas com valor; arrays ordenados por valor (maiores primeiro). */
        PortfolioXray: {
            by_class: (components["schemas"]["PortfolioXraySlice"] & {
                /** @description stock | fii | etf | bdr | tesouro | renda_fixa | debenture | fund | crypto | us | option */
                class: string;
            })[];
            /** @description Só posições de bolsa (ações/FIIs/ETFs/BDRs); sem setor conhecido = 'Sem classificação'. */
            by_sector: (components["schemas"]["PortfolioXraySlice"] & {
                sector: string;
            })[];
            /** @description Exposição da RENDA FIXA por indexador — pct sobre o total de renda fixa, não da carteira. */
            by_indexer: (components["schemas"]["PortfolioXraySlice"] & {
                /** @description selic | ipca | prefixado | cdi | outro */
                indexer: string;
            })[];
            by_currency: (components["schemas"]["PortfolioXraySlice"] & {
                /** @description BRL | USD */
                currency: string;
            })[];
            /** @description As 10 maiores posições por valor. */
            top_positions: (components["schemas"]["PortfolioXraySlice"] & {
                symbol: string;
                class: string;
            })[];
            /** @description Fatos pt-BR quando limites de concentração estouram (posição >10%, setor >25%, classe >60%, indexador >70% da RF, moeda estrangeira >30%). Sem opinião — cite como estão. */
            flags: string[];
            meta: {
                /** @description Base dos percentuais: soma das posições consideradas. */
                patrimonio_brl: number;
                /** @description Base dos percentuais de by_indexer. */
                rf_total_brl: number;
                /** @description Data de referência da valoração (AAAA-MM-DD). */
                reference: string;
                positions_considered: number;
                /** @description Posições abertas sem valor, fora do raio-X. */
                unpriced_ignored: number;
            };
        };
        /** @description Raio-X de custos recorrentes: itens com destinatário e referência, agregação por destinatário, totais e o que ficou sem estimativa (com motivo). Estimativas determinísticas — não é recomendação. */
        PortfolioCosts: {
            /** @description Custos estimados por posição, maiores primeiro. */
            items: {
                /** @description CNPJ da classe (fund), nome do título (tesouro) ou código do papel (renda_fixa). */
                symbol: string;
                /** @description fund | tesouro | renda_fixa */
                class: string;
                name: string | null;
                /** @description Valor da posição (base do custo). */
                value_brl: number;
                /**
                 * @description fund_admin_fee = taxa de administração as-filed; tesouro_custody = custódia B3; rf_cdi_gap = gap estimado de RF tributável contratada abaixo de 100% do CDI.
                 * @enum {string}
                 */
                cost_kind: "fund_admin_fee" | "tesouro_custody" | "rf_cdi_gap";
                /** @description Custo % a.a. efetivo sobre o valor (já líquido de isenção). */
                annual_cost_pct: number | null;
                /** @description Custo estimado em R$/ano. */
                annual_cost_brl: number;
                /** @description Para quem o custo vai (administrador do fundo, B3, emissor/distribuidor). */
                recipient: string;
                /** @description Referência de comparação. Null = sem referência (ex.: custódia; poucos pares). */
                benchmark: {
                    /** @description Ex.: 'mediana dos pares (Renda Fixa)' | '100% do CDI'. */
                    label: string;
                    value_pct: number;
                    /** @description Nº de pares da mediana (só em fund_admin_fee). */
                    peers?: number;
                } | null;
                /** @description Parcela ACIMA da referência (R$/ano). Null = sem referência. */
                excess_cost_brl: number | null;
                /** @description Fato adicional (taxa de performance no cadastro; regra de isenção; base da estimativa). */
                note: string | null;
            }[];
            /** @description Posições SEM estimativa, agregadas por (classe, motivo) — o motivo é parte da resposta. */
            not_estimated: {
                class: string;
                reason: string;
                positions: number;
                /** @description Até 10 símbolos de exemplo. */
                symbols: string[];
            }[];
            /** @description Custo anual agregado por destinatário, maiores primeiro. */
            by_recipient: {
                recipient: string;
                annual_cost_brl: number;
            }[];
            totals: {
                /** @description Soma dos custos estimados (R$/ano). */
                annual_cost_brl: number;
                /** @description Soma do que está acima das referências (mediana dos pares + gap vs CDI). */
                above_reference_brl: number;
                /** @description Custo anual como % do patrimônio considerado. */
                pct_of_patrimonio: number | null;
            };
            /** @description Fatos pt-BR (fundo acima da mediana dos pares; RF abaixo de 100% do CDI). Sem opinião — cite como estão. */
            flags: string[];
            meta: {
                patrimonio_brl: number;
                /** @description Data de referência (AAAA-MM-DD). */
                reference: string;
                positions_considered: number;
                /** @description Posições abertas sem valor, fora da estimativa. */
                unpriced_ignored: number;
                /** @description CDI acumulado 12m usado no gap de RF (%). */
                cdi_12m_pct: number | null;
                /** @description O que a estimativa cobre e o que fica de fora — repasse ao usuário. */
                caveat: string;
            };
        };
        /** @description Exposição efetiva: posições em fundos abertas na última carteira mensal divulgada de cada um (defasada — não é a posição de hoje). Exposição indireta é PISO: cobre só o que o fundo divulgou. */
        PortfolioLookThrough: {
            /** @description Ativos alcançados VIA FUNDOS, com a posição direta ao lado (top 50 por valor total). */
            exposures: {
                /** @description Ticker (kind=stock) ou código da debênture (kind=debenture). */
                symbol: string;
                /** @enum {string} */
                kind: "stock" | "debenture";
                /** @description Posição direta da carteira no mesmo ativo (0 = só via fundos). */
                direct_value_brl: number;
                /** @description Exposição proporcional via fundos. */
                indirect_value_brl: number;
                total_value_brl: number;
                /** @description total_value_brl ÷ patrimônio, 0-100. */
                pct_of_portfolio: number | null;
                /** @description Por quais fundos DA CARTEIRA a exposição chega (2º nível de FoF atribuído ao fundo direto). */
                via: {
                    fund_cnpj: string;
                    fund_name: string | null;
                    value_brl: number;
                }[];
            }[];
            funds_opened: {
                fund_cnpj: string;
                fund_name: string | null;
                /** @description Valor da posição no fundo (BRL). */
                position_value_brl: number;
                /** @description Competência da carteira divulgada usada (AAAA-MM-DD). */
                comptc_date: string | null;
                /** @description Quanto do fundo os ativos divulgados explicam (0-100; pode passar de 100 por descasamento de datas). */
                coverage_pct: number | null;
                /**
                 * @description Denominador dos pesos: patrimônio oficial na competência (pl) ou soma dos ativos divulgados (disclosed_sum, quando o patrimônio falta — coverage vira 100 por construção).
                 * @enum {string}
                 */
                method: "pl" | "disclosed_sum";
            }[];
            /** @description Posições em fundo que NÃO puderam ser abertas (sem carteira divulgada ou sem valor). */
            not_opened: {
                /** @description CNPJ do fundo. */
                symbol: string;
                fund_name: string | null;
                position_value_brl: number | null;
                reason: string;
            }[];
            meta: {
                patrimonio_brl: number;
                /** @description Competências das carteiras divulgadas usadas. */
                comptc_dates: string[];
                /** @description Linhas além do top 50 (ausente quando não truncou). */
                exposures_truncated?: number;
                /** @description Presente quando a carteira não tem fundos (resposta válida, vazia). */
                note?: string;
                /** @description Limitação metodológica — repasse ao usuário quando relevante. */
                caveat: string;
            };
        };
        /** @description Resumo de um import de planilha (o detalhe linha a linha fica em listPortfolioImportRows). */
        PortfolioImportSummary: {
            import_id: string;
            /** @description negociacao | movimentacao | manual (detectado pelo cabeçalho). */
            source: string;
            /** @description Linhas entendidas no arquivo. */
            parsed?: number;
            /** @description Lançamentos novos gravados. */
            imported: number;
            /** @description Lançamentos já existentes (reimport) pulados. */
            duplicates_skipped?: number;
            rows_ignored?: number;
            /** @description Trades pulados por já estarem cobertos por outra fonte. */
            cross_source_skipped?: number;
            symbols?: number;
            period?: {
                from?: string | null;
                to?: string | null;
            };
            /** @description Até 10 avisos. */
            warnings?: string[];
            /** @description Nº de avisos omitidos além dos 10 primeiros. */
            warnings_truncated?: number;
        };
        PortfolioImportListItem: {
            id: string;
            filename?: string | null;
            source: string;
            /** Format: date-time */
            created_at?: string;
            summary?: Record<string, never>;
            warnings?: string[];
        };
        PortfolioImportRow: {
            row_index: number;
            /** @description imported | ignored | duplicate | error */
            status: string;
            kind?: string | null;
            label?: string | null;
            reason?: string | null;
            external_id?: string | null;
            raw?: unknown;
        };
        /** @description Posição resumida do consolidado (o detalhe completo vem em getPortfolioDetail). */
        PortfolioPosition: {
            symbol: string;
            asset_type: string;
            qty: number;
            weight_pct?: number | null;
            market_value?: number | null;
            unrealized_pct?: number | null;
        };
        /** @description Carteira consolidada do usuário (mesmo resumo que o agente de IA usa). */
        PortfolioContext: {
            has_portfolio: boolean;
            carteiras: number;
            patrimonio: number;
            invested: number;
            unrealized_pl: number;
            unrealized_pct: number;
            realized_pl: number;
            /** @description XIRR (TIR anualizada, money-weighted) do consolidado. Decimal a.a. (0,14 = 14%). */
            xirr?: number | null;
            day_change_brl: number;
            kind_mix: string;
            any_unpriced: boolean;
            /** @description Todas as posições consolidadas (qty > 0), ordenadas por valor (maiores primeiro). */
            positions: components["schemas"]["PortfolioPosition"][];
            by_carteira: components["schemas"]["PortfolioByCarteira"][];
        };
        Problem: {
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /** @description O erro em forma legível por programa (`code`, valores recebidos, tetos). */
            details?: {
                [key: string]: unknown;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getPortfolio: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Carteira consolidada do usuário. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioContext"];
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getPortfolioHistory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pontos mensais em `data`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioHistoryResponse"];
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listPortfolios: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Carteiras da conta. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PortfolioListItem"][];
                        meta: {
                            /** @description Sempre null: resposta em página única. */
                            next_cursor: string | null;
                            /** @description Itens nesta página. */
                            count: number;
                        };
                    };
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    createPortfolio: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Nome da carteira (até 60 caracteres, único na conta). */
                    name: string;
                    /**
                     * @description Visibilidade (default private).
                     * @enum {string}
                     */
                    visibility?: "private" | "unlisted" | "public";
                };
            };
        };
        responses: {
            /** @description Carteira criada. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioListItem"];
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getPortfolioImportTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Arquivo CSV. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getPortfolioDetail: {
        parameters: {
            query?: {
                /** @description Camadas separadas por vírgula: `closed` inclui posições encerradas; `monthly`, séries mensais por posição; `transactions`, o ledger completo e potencialmente volumoso. */
                include?: string;
            };
            header?: never;
            path: {
                /** @description Id da carteira (de listPortfolios). */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Carteira computada. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioDetail"];
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    deletePortfolio: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id da carteira. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Carteira apagada. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        deleted?: boolean;
                        id?: string;
                    };
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    updatePortfolio: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id da carteira. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Novo nome (até 60 caracteres, único na conta). */
                    name?: string;
                    /**
                     * @description Nova visibilidade.
                     * @enum {string}
                     */
                    visibility?: "private" | "unlisted" | "public";
                    /** @description true = carteira de simulação (fora do consolidado). */
                    exclude_from_consolidated?: boolean;
                };
            };
        };
        responses: {
            /** @description Campos alterados. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getPortfolioHistoryById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id da carteira. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pontos mensais em `data`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioHistoryDetailResponse"];
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getPortfolioXray: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id da carteira (de listPortfolios). */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Raio-X da carteira. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioXray"];
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getPortfolioCosts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id da carteira (de listPortfolios). */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Raio-X de custos da carteira. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioCosts"];
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getPortfolioLookThrough: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id da carteira (de listPortfolios). */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Exposição efetiva da carteira. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioLookThrough"];
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    addPortfolioAsset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id da carteira. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description O objeto do grafo (`pub_…`). Dispensa asset_type/symbol; recusado com o motivo quando o objeto não entra na carteira. */
                    entity_id?: string;
                    /**
                     * @description Tipo do ativo (com symbol; dispensável com entity_id).
                     * @enum {string}
                     */
                    asset_type?: "stock" | "fii" | "etf" | "bdr" | "index" | "tesouro" | "crypto" | "option" | "renda_fixa" | "debenture" | "fund" | "us";
                    /** @description Ticker (ex.: PETR4) ou nome oficial do título do Tesouro (com asset_type; dispensável com entity_id). */
                    symbol?: string;
                };
            };
        };
        responses: {
            /** @description Ativo na carteira. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    removePortfolioAsset: {
        parameters: {
            query?: {
                /** @description O objeto do grafo (`pub_…`); dispensa asset_type/symbol. */
                entity_id?: string;
                /** @description Tipo do ativo. Com symbol; dispensável com entity_id. */
                asset_type?: "stock" | "fii" | "etf" | "bdr" | "index" | "tesouro" | "crypto" | "option" | "renda_fixa" | "debenture" | "fund" | "us";
                /** @description Ticker ou nome do título. */
                symbol?: string;
            };
            header?: never;
            path: {
                /** @description Id da carteira. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ativo removido. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    updatePortfolioAsset: {
        parameters: {
            query?: {
                /** @description O objeto do grafo (`pub_…`); dispensa asset_type/symbol. */
                entity_id?: string;
                /** @description Tipo do ativo (renda_fixa/tesouro). Com symbol; dispensável com entity_id. */
                asset_type?: string;
                /** @description Código do papel. */
                symbol?: string;
            };
            header?: never;
            path: {
                /** @description Id da carteira. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description Indexador (none limpa a taxa).
                     * @enum {string}
                     */
                    rf_indexer: "cdi" | "prefixado" | "ipca" | "none";
                    /** @description Taxa (ex.: 110 = 110% do CDI; 6.2 = IPCA+6,2%). */
                    rf_rate?: number;
                };
            };
        };
        responses: {
            /** @description Meta da posição. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listPortfolioTransactions: {
        parameters: {
            query?: {
                /** @description O objeto do grafo (`pub_…`); dispensa asset_type/symbol. */
                entity_id?: string;
                /** @description Tipo do ativo. Com symbol; dispensável com entity_id. */
                asset_type?: string;
                /** @description Ticker ou nome do título. */
                symbol?: string;
            };
            header?: never;
            path: {
                /** @description Id da carteira. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Transações do ativo. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PortfolioTransaction"][];
                        meta: {
                            /** @description Sempre null: resposta em página única. */
                            next_cursor: string | null;
                            /** @description Itens nesta página. */
                            count: number;
                            /** @description Ativo do ledger (id, asset_type, symbol). */
                            asset?: Record<string, never>;
                        };
                    };
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    addPortfolioTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id da carteira. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description O objeto do grafo (`pub_…`). Dispensa asset_type/symbol. */
                    entity_id?: string;
                    /**
                     * @description Tipo do ativo (com symbol; dispensável com entity_id).
                     * @enum {string}
                     */
                    asset_type?: "stock" | "fii" | "etf" | "bdr" | "index" | "tesouro" | "crypto" | "option" | "renda_fixa" | "debenture" | "fund" | "us";
                    /** @description Ticker (ex.: PETR4) ou nome oficial do título do Tesouro (com asset_type; dispensável com entity_id). */
                    symbol?: string;
                    /**
                     * @description Tipo da transação.
                     * @enum {string}
                     */
                    kind: "buy" | "sell" | "split";
                    /** @description Data do negócio (AAAA-MM-DD). */
                    trade_date: string;
                    /** @description Quantidade (> 0; obrigatória em buy/sell). */
                    quantity?: number;
                    /** @description Preço unitário em BRL (omita se desconhecido). */
                    price?: number;
                    /** @description Custos/corretagem em BRL (default 0). */
                    fees?: number;
                    /** @description Fator do split (2 = 2:1; 0.5 = grupamento 1:2). */
                    ratio?: number;
                    /** @description Observação livre (até 280 caracteres). */
                    note?: string;
                };
            };
        };
        responses: {
            /** @description Transação lançada. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        transaction?: components["schemas"]["PortfolioTransaction"];
                    };
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    deletePortfolioTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id da carteira. */
                id: string;
                /** @description Id da transação. */
                txId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Transação removida. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        deleted?: boolean;
                        id?: string;
                    };
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    updatePortfolioTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id da carteira. */
                id: string;
                /** @description Id da transação (de listPortfolioTransactions). */
                txId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description Tipo da transação.
                     * @enum {string}
                     */
                    kind?: "buy" | "sell" | "split";
                    /** @description Data do negócio (AAAA-MM-DD). */
                    trade_date?: string;
                    /** @description Quantidade. */
                    quantity?: number;
                    /** @description Preço unitário em BRL. */
                    price?: number;
                    /** @description Custos em BRL. */
                    fees?: number;
                    /** @description Fator do split. */
                    ratio?: number;
                    /** @description Observação. */
                    note?: string;
                };
            };
        };
        responses: {
            /** @description Transação atualizada. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioTransaction"];
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listPortfolioImports: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id da carteira. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Imports da carteira. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PortfolioImportListItem"][];
                        meta: {
                            /** @description Sempre null: resposta em página única. */
                            next_cursor: string | null;
                            /** @description Itens nesta página. */
                            count: number;
                        };
                    };
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    importPortfolioFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id da carteira. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Conteúdo do arquivo em base64. */
                    content_base64: string;
                    /** @description Nome do arquivo (ajuda a trilha de auditoria). */
                    filename?: string;
                };
            };
        };
        responses: {
            /** @description Resumo do import. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioImportSummary"];
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listPortfolioImportRows: {
        parameters: {
            query?: {
                /** @description Filtra por status. */
                status?: "imported" | "ignored" | "duplicate" | "error";
                /** @description Linhas por página (1–500, default 100). */
                limit?: number;
                /** @description Cursor opaco de meta.next_cursor — mesma paginação das demais listagens. */
                cursor?: string;
            };
            header?: never;
            path: {
                /** @description Id da carteira. */
                id: string;
                /** @description Id do import (de listPortfolioImports). */
                importId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Linhas do import. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PortfolioImportRow"][];
                        meta: {
                            /** @description Sempre null: resposta em página única. */
                            next_cursor: string | null;
                            /** @description Itens nesta página. */
                            count: number;
                            /** @description Linhas do import que casam o filtro, antes do recorte da página. */
                            total?: number;
                        };
                    };
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    reconcilePortfolioAsset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id da carteira. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Tipo do ativo. */
                    asset_type: string;
                    /** @description Ticker. */
                    symbol: string;
                    /** @description Quantidade declarada pela B3 (>= 0). */
                    target_qty: number;
                    /** @description Data de referência (AAAA-MM-DD). */
                    as_of: string;
                };
            };
        };
        responses: {
            /** @description Resultado do ajuste (delta aplicado). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getSuitability: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Perfil de investidor do usuário (ou nulo). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuitabilityEnvelope"];
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
