/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/advisor/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Identidade do chamador e organizações acessíveis
         * @description Com credencial pessoal de membro, lista as organizações em que o usuário tem assento. Com chave de organização, retorna a própria organização da chave.
         */
        get: operations["advisorGetMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/advisor/invitations/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Aceitar convite de organização */
        post: operations["advisorAcceptInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/advisor/orgs/{org}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalhe da organização */
        get: operations["advisorGetOrganization"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Atualizar nome/configurações da organização
         * @description Inclui `settings.client_visibility`: `all` (todos veem todos os clientes) ou `assigned` (assessor/viewer só veem clientes atribuídos).
         */
        patch: operations["advisorUpdateOrganization"];
        trace?: never;
    };
    "/v1/advisor/orgs/{org}/license": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Licença e limites vigentes */
        get: operations["advisorGetLicense"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/advisor/orgs/{org}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Membros da organização */
        get: operations["advisorListMembers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/advisor/orgs/{org}/members/{memberId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Atualizar papel/status de um membro */
        patch: operations["advisorUpdateMember"];
        trace?: never;
    };
    "/v1/advisor/orgs/{org}/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Convites da organização */
        get: operations["advisorListInvitations"];
        put?: never;
        /** Convidar membro (e-mail + papel) */
        post: operations["advisorCreateInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/advisor/orgs/{org}/invitations/{invitationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revogar convite pendente */
        delete: operations["advisorRevokeInvitation"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/advisor/orgs/{org}/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Visão geral da organização (agregados)
         * @description AUM total, clientes, alocação por classe, quebra por assessor (owner/admin) e atividade recente. O escopo é aplicado no servidor: assessor com visibilidade `assigned` recebe o agregado apenas dos clientes atribuídos a ele. Carteiras `proposal` nunca entram nos agregados.
         */
        get: operations["advisorGetOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/advisor/orgs/{org}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Trilha de auditoria (paginada)
         * @description Eventos da organização em ordem decrescente, com keyset pagination (`cursor` opaco). `client_id` filtra o cliente e suas carteiras. Assessor com visibilidade `assigned` vê apenas eventos dos clientes atribuídos.
         */
        get: operations["advisorListAuditLog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/advisor/orgs/{org}/families": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Famílias da organização */
        get: operations["advisorListFamilies"];
        put?: never;
        /** Criar família (agrupamento de clientes) */
        post: operations["advisorCreateFamily"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/advisor/orgs/{org}/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Clientes visíveis ao chamador
         * @description Com `settings.client_visibility = assigned`, assessor/viewer só veem clientes atribuídos a eles.
         */
        get: operations["advisorListClients"];
        put?: never;
        /** Cadastrar cliente */
        post: operations["advisorCreateClient"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/advisor/orgs/{org}/clients/{clientId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalhe do cliente (cadastro + perfil + responsável) */
        get: operations["advisorGetClient"];
        put?: never;
        post?: never;
        /**
         * Excluir cliente (remoção real, com carteiras e perfil)
         * @description Correção de cadastro errado. Para fim de relação, prefira `PATCH status: offboarded` (arquiva preservando histórico).
         */
        delete: operations["advisorDeleteClient"];
        options?: never;
        head?: never;
        /** Atualizar cadastro/status do cliente */
        patch: operations["advisorUpdateClient"];
        trace?: never;
    };
    "/v1/advisor/orgs/{org}/clients/{clientId}/assignment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Definir assessor responsável */
        put: operations["advisorSetClientAssignment"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/advisor/orgs/{org}/clients/{clientId}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Atualizar objetivos/restrições/contexto do cliente
         * @description O perfil é o contexto que agente, MCP e relatórios leem. Histórico via trilha de auditoria.
         */
        put: operations["advisorUpdateClientProfile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/advisor/orgs/{org}/clients/{clientId}/portfolios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Carteiras de um cliente */
        get: operations["advisorListClientPortfolios"];
        put?: never;
        /**
         * Criar carteira para um cliente
         * @description `kind: proposal` marca estudo/realocação — fica fora do consolidado do cliente.
         */
        post: operations["advisorCreateClientPortfolio"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/advisor/orgs/{org}/portfolios/{portfolioId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Posições e valorização da carteira
         * @description Posição derivada do ledger no motor de cálculo; cotações do DataBolsa Core.
         */
        get: operations["advisorGetClientPortfolio"];
        put?: never;
        post?: never;
        /** Remover carteira */
        delete: operations["advisorDeleteClientPortfolio"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/advisor/orgs/{org}/portfolios/{portfolioId}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Evolução mensal e retornos da carteira
         * @description Curva mensal de patrimônio × aporte derivada do ledger (mesmo motor do DataBolsa), com TWR e XIRR. Renda fixa entra pelo custo remanescente.
         */
        get: operations["advisorGetClientPortfolioHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/advisor/orgs/{org}/clients/{clientId}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Evolução mensal e retornos consolidados do cliente
         * @description Consolida as carteiras reais do cliente (propostas ficam fora), com TWR e XIRR.
         */
        get: operations["advisorGetClientHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/advisor/orgs/{org}/portfolios/{portfolioId}/ledger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ativos e lançamentos (ledger) da carteira */
        get: operations["advisorGetClientPortfolioLedger"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/advisor/orgs/{org}/portfolios/{portfolioId}/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Importar planilha no ledger da carteira
         * @description Multipart com campo `file` (.xlsx ou .csv). Auto-detecta Negociação/Movimentação da B3 e o template manual; idempotente por linha (reimportar não duplica).
         */
        post: operations["advisorImportClientPortfolioFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/advisor/orgs/{org}/portfolios/{portfolioId}/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Adicionar ativo à carteira */
        post: operations["advisorAddClientPortfolioAsset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/advisor/orgs/{org}/portfolios/{portfolioId}/assets/{assetId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remover ativo (e seu ledger) da carteira */
        delete: operations["advisorRemoveClientPortfolioAsset"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/advisor/orgs/{org}/portfolios/{portfolioId}/assets/{assetId}/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Lançar transação no ledger do ativo */
        post: operations["advisorAddClientPortfolioTransaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/advisor/orgs/{org}/portfolios/{portfolioId}/transactions/{txId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remover lançamento do ledger */
        delete: operations["advisorDeleteClientPortfolioTransaction"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/advisor/orgs/{org}/keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chaves de API da organização */
        get: operations["advisorListOrgKeys"];
        put?: never;
        /**
         * Emitir chave de organização (db_org_...)
         * @description A chave completa é retornada UMA única vez. `key_role: read` limita a leituras; `full` opera como admin. Chave de organização enxerga todos os clientes.
         */
        post: operations["advisorCreateOrgKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/advisor/orgs/{org}/keys/{keyId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revogar chave de organização */
        delete: operations["advisorRevokeOrgKey"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    advisorGetMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        principal: "member" | "org_key";
                        user_id: string | null;
                        organizations: {
                            org_id: string;
                            org_slug: string;
                            org_name: string;
                            /** @enum {string} */
                            role: "owner" | "admin" | "advisor" | "viewer";
                            member_id: string;
                        }[];
                    };
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type?: string;
                        title: string;
                        status: number;
                        detail?: string;
                        code?: string;
                    };
                };
            };
        };
    };
    advisorAcceptInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    token: string;
                };
            };
        };
        responses: {
            /** @description Assento criado/reativado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        org_id: string;
                        org_slug: string;
                        member_id: string;
                        role: string;
                    };
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type?: string;
                        title: string;
                        status: number;
                        detail?: string;
                        code?: string;
                    };
                };
            };
        };
    };
    advisorGetOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        slug: string;
                        name: string;
                        cnpj: string | null;
                        cvm_registration: string | null;
                        status: string;
                        settings: {
                            /** @enum {string} */
                            client_visibility: "all" | "assigned";
                        };
                        created_at: string;
                    };
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type?: string;
                        title: string;
                        status: number;
                        detail?: string;
                        code?: string;
                    };
                };
            };
        };
    };
    advisorUpdateOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    name?: string;
                    settings?: {
                        /** @enum {string} */
                        client_visibility?: "all" | "assigned";
                    };
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        slug: string;
                        name: string;
                        cnpj: string | null;
                        cvm_registration: string | null;
                        status: string;
                        settings: {
                            /** @enum {string} */
                            client_visibility: "all" | "assigned";
                        };
                        created_at: string;
                    };
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type?: string;
                        title: string;
                        status: number;
                        detail?: string;
                        code?: string;
                    };
                };
            };
        };
    };
    advisorGetLicense: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        plan: string | null;
                        seats_limit: number;
                        clients_limit: number | null;
                        expires_at: string | null;
                        expired: boolean;
                    };
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type?: string;
                        title: string;
                        status: number;
                        detail?: string;
                        code?: string;
                    };
                };
            };
        };
    };
    advisorListMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            user_id: string;
                            /** @enum {string} */
                            role: "owner" | "admin" | "advisor" | "viewer";
                            display_name: string | null;
                            status: string;
                            created_at: string;
                        }[];
                    };
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type?: string;
                        title: string;
                        status: number;
                        detail?: string;
                        code?: string;
                    };
                };
            };
        };
    };
    advisorUpdateMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org: string;
                memberId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    role?: "owner" | "admin" | "advisor";
                    /** @enum {string} */
                    status?: "active" | "suspended";
                    display_name?: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        user_id: string;
                        /** @enum {string} */
                        role: "owner" | "admin" | "advisor" | "viewer";
                        display_name: string | null;
                        status: string;
                        created_at: string;
                    };
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type?: string;
                        title: string;
                        status: number;
                        detail?: string;
                        code?: string;
                    };
                };
            };
        };
    };
    advisorListInvitations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            email: string;
                            /** @enum {string} */
                            role: "owner" | "admin" | "advisor" | "viewer";
                            status: string;
                            expires_at: string;
                            created_at: string;
                        }[];
                    };
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type?: string;
                        title: string;
                        status: number;
                        detail?: string;
                        code?: string;
                    };
                };
            };
        };
    };
    advisorCreateInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    /** @enum {string} */
                    role: "owner" | "admin" | "advisor";
                };
            };
        };
        responses: {
            /** @description Convite criado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        invitation_id: string;
                        invite_url: string;
                    };
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type?: string;
                        title: string;
                        status: number;
                        detail?: string;
                        code?: string;
                    };
                };
            };
        };
    };
    advisorRevokeInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org: string;
                invitationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        revoked: boolean;
                    };
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type?: string;
                        title: string;
                        status: number;
                        detail?: string;
                        code?: string;
                    };
                };
            };
        };
    };
    advisorGetOverview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        aum_total: number | null;
                        clients: {
                            total: number;
                            prospect: number;
                            active: number;
                        };
                        by_class: {
                            asset_type: string;
                            market_value: number;
                        }[];
                        by_advisor: {
                            member_id: string | null;
                            display_name: string | null;
                            clients: number;
                            aum: number | null;
                        }[] | null;
                        by_client: {
                            client_id: string;
                            name: string;
                            status: string;
                            owner_member_id: string | null;
                            owner_display_name: string | null;
                            aum: number | null;
                            portfolios: number;
                        }[];
                        recent_activity: {
                            id: string;
                            action: string;
                            summary: string | null;
                            via: string;
                            actor_member_id: string | null;
                            actor_display_name: string | null;
                            entity_type: string | null;
                            entity_id: string | null;
                            created_at: string;
                        }[];
                    };
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type?: string;
                        title: string;
                        status: number;
                        detail?: string;
                        code?: string;
                    };
                };
            };
        };
    };
    advisorListAuditLog: {
        parameters: {
            query?: {
                client_id?: string;
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path: {
                org: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            action: string;
                            summary: string | null;
                            via: string;
                            actor_member_id: string | null;
                            actor_display_name: string | null;
                            entity_type: string | null;
                            entity_id: string | null;
                            created_at: string;
                        }[];
                        next_cursor: string | null;
                    };
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type?: string;
                        title: string;
                        status: number;
                        detail?: string;
                        code?: string;
                    };
                };
            };
        };
    };
    advisorListFamilies: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            name: string;
                            note: string | null;
                            created_at: string;
                        }[];
                    };
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type?: string;
                        title: string;
                        status: number;
                        detail?: string;
                        code?: string;
                    };
                };
            };
        };
    };
    advisorCreateFamily: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    name: string;
                    note?: string;
                };
            };
        };
        responses: {
            /** @description Família criada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        name: string;
                        note: string | null;
                        created_at: string;
                    };
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type?: string;
                        title: string;
                        status: number;
                        detail?: string;
                        code?: string;
                    };
                };
            };
        };
    };
    advisorListClients: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            /** @enum {string} */
                            kind: "person" | "entity";
                            name: string;
                            email: string | null;
                            phone: string | null;
                            document_id: string | null;
                            family_id: string | null;
                            /** @enum {string} */
                            status: "prospect" | "active" | "inactive" | "offboarded";
                            created_at: string;
                        }[];
                    };
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type?: string;
                        title: string;
                        status: number;
                        detail?: string;
                        code?: string;
                    };
                };
            };
        };
    };
    advisorCreateClient: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    name: string;
                    /** @enum {string} */
                    kind?: "person" | "entity";
                    /** Format: email */
                    email?: string | null;
                    phone?: string | null;
                    document_id?: string | null;
                    family_id?: string | null;
                    /** @enum {string} */
                    status?: "prospect" | "active";
                    owner_member_id?: string | null;
                };
            };
        };
        responses: {
            /** @description Cliente criado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        /** @enum {string} */
                        kind: "person" | "entity";
                        name: string;
                        email: string | null;
                        phone: string | null;
                        document_id: string | null;
                        family_id: string | null;
                        /** @enum {string} */
                        status: "prospect" | "active" | "inactive" | "offboarded";
                        created_at: string;
                    };
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type?: string;
                        title: string;
                        status: number;
                        detail?: string;
                        code?: string;
                    };
                };
            };
        };
    };
    advisorGetClient: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org: string;
                clientId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        client: {
                            id: string;
                            /** @enum {string} */
                            kind: "person" | "entity";
                            name: string;
                            email: string | null;
                            phone: string | null;
                            document_id: string | null;
                            family_id: string | null;
                            /** @enum {string} */
                            status: "prospect" | "active" | "inactive" | "offboarded";
                            created_at: string;
                        };
                        profile: {
                            objectives: {
                                kind: string;
                                description?: string;
                                target_amount_cents?: number;
                                target_date?: string;
                            }[];
                            restrictions: {
                                /** @enum {string} */
                                kind: "no_asset" | "no_class" | "max_allocation" | "liquidity" | "other";
                                symbol?: string;
                                asset_class?: string;
                                max_pct?: number;
                                description?: string;
                            }[];
                            risk_profile: string | null;
                            suitability?: null;
                            horizon: string | null;
                            notes: string | null;
                            updated_at: string | null;
                        } | null;
                        assignments: {
                            member_id: string;
                            member_display_name: string | null;
                            role: string;
                        }[];
                    };
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type?: string;
                        title: string;
                        status: number;
                        detail?: string;
                        code?: string;
                    };
                };
            };
        };
    };
    advisorDeleteClient: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org: string;
                clientId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        deleted: boolean;
                    };
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type?: string;
                        title: string;
                        status: number;
                        detail?: string;
                        code?: string;
                    };
                };
            };
        };
    };
    advisorUpdateClient: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org: string;
                clientId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    name?: string;
                    /** @enum {string} */
                    kind?: "person" | "entity";
                    /** Format: email */
                    email?: string | null;
                    phone?: string | null;
                    document_id?: string | null;
                    family_id?: string | null;
                    /** @enum {string} */
                    status?: "prospect" | "active" | "inactive" | "offboarded";
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        /** @enum {string} */
                        kind: "person" | "entity";
                        name: string;
                        email: string | null;
                        phone: string | null;
                        document_id: string | null;
                        family_id: string | null;
                        /** @enum {string} */
                        status: "prospect" | "active" | "inactive" | "offboarded";
                        created_at: string;
                    };
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type?: string;
                        title: string;
                        status: number;
                        detail?: string;
                        code?: string;
                    };
                };
            };
        };
    };
    advisorSetClientAssignment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org: string;
                clientId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    member_id: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        updated: boolean;
                    };
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type?: string;
                        title: string;
                        status: number;
                        detail?: string;
                        code?: string;
                    };
                };
            };
        };
    };
    advisorUpdateClientProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org: string;
                clientId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    objectives?: {
                        kind: string;
                        description?: string;
                        target_amount_cents?: number;
                        target_date?: string;
                    }[];
                    restrictions?: {
                        /** @enum {string} */
                        kind: "no_asset" | "no_class" | "max_allocation" | "liquidity" | "other";
                        symbol?: string;
                        asset_class?: string;
                        max_pct?: number;
                        description?: string;
                    }[];
                    risk_profile?: string | null;
                    suitability?: unknown;
                    horizon?: string | null;
                    notes?: string | null;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        objectives: {
                            kind: string;
                            description?: string;
                            target_amount_cents?: number;
                            target_date?: string;
                        }[];
                        restrictions: {
                            /** @enum {string} */
                            kind: "no_asset" | "no_class" | "max_allocation" | "liquidity" | "other";
                            symbol?: string;
                            asset_class?: string;
                            max_pct?: number;
                            description?: string;
                        }[];
                        risk_profile: string | null;
                        suitability?: null;
                        horizon: string | null;
                        notes: string | null;
                        updated_at: string | null;
                    };
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type?: string;
                        title: string;
                        status: number;
                        detail?: string;
                        code?: string;
                    };
                };
            };
        };
    };
    advisorListClientPortfolios: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org: string;
                clientId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            client_id: string;
                            name: string;
                            /** @enum {string} */
                            kind: "actual" | "proposal";
                            base_currency: string;
                            created_at: string;
                        }[];
                    };
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type?: string;
                        title: string;
                        status: number;
                        detail?: string;
                        code?: string;
                    };
                };
            };
        };
    };
    advisorCreateClientPortfolio: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org: string;
                clientId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    name: string;
                    /** @enum {string} */
                    kind?: "actual" | "proposal";
                    base_currency?: string;
                };
            };
        };
        responses: {
            /** @description Carteira criada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        client_id: string;
                        name: string;
                        /** @enum {string} */
                        kind: "actual" | "proposal";
                        base_currency: string;
                        created_at: string;
                    };
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type?: string;
                        title: string;
                        status: number;
                        detail?: string;
                        code?: string;
                    };
                };
            };
        };
    };
    advisorGetClientPortfolio: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org: string;
                portfolioId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        portfolio: {
                            id: string;
                            client_id: string;
                            name: string;
                            /** @enum {string} */
                            kind: "actual" | "proposal";
                            base_currency: string;
                            created_at: string;
                        };
                        holdings: {
                            asset_type: string;
                            symbol: string;
                            name: string;
                            qty: number;
                            avg: number | null;
                            invested_cost: number | null;
                            cost_basis_known: boolean;
                            price: number | null;
                            change_pct: number | null;
                            market_value: number | null;
                            unrealized_pl: number | null;
                            unrealized_pct: number | null;
                            tx_count: number;
                        }[];
                        totals: {
                            market_value: number | null;
                            invested_cost: number | null;
                            unrealized_pl: number | null;
                        };
                    };
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type?: string;
                        title: string;
                        status: number;
                        detail?: string;
                        code?: string;
                    };
                };
            };
        };
    };
    advisorDeleteClientPortfolio: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org: string;
                portfolioId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        deleted: boolean;
                    };
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type?: string;
                        title: string;
                        status: number;
                        detail?: string;
                        code?: string;
                    };
                };
            };
        };
    };
    advisorGetClientPortfolioHistory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org: string;
                portfolioId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        points: {
                            month: string;
                            patrimonio: number;
                            aporte: number;
                            proventos: number;
                            realizado: number;
                        }[];
                        twr: {
                            cumulative: number;
                            annualized: number | null;
                            months: number;
                        } | null;
                        xirr: number | null;
                        returns_explain: string;
                    };
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type?: string;
                        title: string;
                        status: number;
                        detail?: string;
                        code?: string;
                    };
                };
            };
        };
    };
    advisorGetClientHistory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org: string;
                clientId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        points: {
                            month: string;
                            patrimonio: number;
                            aporte: number;
                            proventos: number;
                            realizado: number;
                        }[];
                        twr: {
                            cumulative: number;
                            annualized: number | null;
                            months: number;
                        } | null;
                        xirr: number | null;
                        returns_explain: string;
                    };
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type?: string;
                        title: string;
                        status: number;
                        detail?: string;
                        code?: string;
                    };
                };
            };
        };
    };
    advisorGetClientPortfolioLedger: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org: string;
                portfolioId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            asset: {
                                id: string;
                                asset_type: string;
                                symbol: string;
                                note: string | null;
                            };
                            transactions: {
                                id: string;
                                kind: string;
                                trade_date: string;
                                quantity: number;
                                price: number | null;
                                fees: number;
                                ratio: number | null;
                                note: string | null;
                                external_id: string | null;
                            }[];
                        }[];
                    };
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type?: string;
                        title: string;
                        status: number;
                        detail?: string;
                        code?: string;
                    };
                };
            };
        };
    };
    advisorImportClientPortfolioFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org: string;
                portfolioId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resumo do import */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        source: "negociacao" | "movimentacao" | "manual";
                        parsed: number;
                        imported: number;
                        duplicates_skipped: number;
                        symbols: string[];
                        warnings: string[];
                        period: {
                            from: string | null;
                            to: string | null;
                        } | null;
                    };
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type?: string;
                        title: string;
                        status: number;
                        detail?: string;
                        code?: string;
                    };
                };
            };
        };
    };
    advisorAddClientPortfolioAsset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org: string;
                portfolioId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    asset_type: string;
                    symbol: string;
                    note?: string | null;
                    meta?: unknown;
                };
            };
        };
        responses: {
            /** @description Ativo adicionado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        asset_type: string;
                        symbol: string;
                        note: string | null;
                    };
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type?: string;
                        title: string;
                        status: number;
                        detail?: string;
                        code?: string;
                    };
                };
            };
        };
    };
    advisorRemoveClientPortfolioAsset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org: string;
                portfolioId: string;
                assetId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        deleted: boolean;
                    };
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type?: string;
                        title: string;
                        status: number;
                        detail?: string;
                        code?: string;
                    };
                };
            };
        };
    };
    advisorAddClientPortfolioTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org: string;
                portfolioId: string;
                assetId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    kind: "buy" | "sell" | "split";
                    trade_date: string;
                    quantity: number;
                    price?: number | null;
                    fees?: number;
                    ratio?: number | null;
                    note?: string | null;
                    external_id?: string | null;
                };
            };
        };
        responses: {
            /** @description Lançamento criado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        kind: string;
                        trade_date: string;
                        quantity: number;
                        price: number | null;
                        fees: number;
                        ratio: number | null;
                        note: string | null;
                        external_id: string | null;
                    };
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type?: string;
                        title: string;
                        status: number;
                        detail?: string;
                        code?: string;
                    };
                };
            };
        };
    };
    advisorDeleteClientPortfolioTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org: string;
                portfolioId: string;
                txId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        deleted: boolean;
                    };
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type?: string;
                        title: string;
                        status: number;
                        detail?: string;
                        code?: string;
                    };
                };
            };
        };
    };
    advisorListOrgKeys: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            name: string;
                            prefix: string;
                            last4: string;
                            /** @enum {string} */
                            key_role: "full" | "read";
                            created_at: string;
                            last_used_at: string | null;
                            revoked_at: string | null;
                        }[];
                    };
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type?: string;
                        title: string;
                        status: number;
                        detail?: string;
                        code?: string;
                    };
                };
            };
        };
    };
    advisorCreateOrgKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    name: string;
                    /** @enum {string} */
                    key_role?: "full" | "read";
                };
            };
        };
        responses: {
            /** @description Chave emitida */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        key: string;
                        record: {
                            id: string;
                            name: string;
                            prefix: string;
                            last4: string;
                            /** @enum {string} */
                            key_role: "full" | "read";
                            created_at: string;
                            last_used_at: string | null;
                            revoked_at: string | null;
                        };
                    };
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type?: string;
                        title: string;
                        status: number;
                        detail?: string;
                        code?: string;
                    };
                };
            };
        };
    };
    advisorRevokeOrgKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org: string;
                keyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        revoked: boolean;
                    };
                };
            };
            /** @description Erro (RFC 9457 application/problem+json) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type?: string;
                        title: string;
                        status: number;
                        detail?: string;
                        code?: string;
                    };
                };
            };
        };
    };
}
